### ISSUE TITLE
`WeakObserver` does not work properly

### ISSUE THREAD

**Issue by mrakgr** [tamirdresher/RxInAction#5]
```
Collecting and sleeping for 2 seconds
Interval - OnNext(0)
Done sleeping
removing the strong reference, collecting and sleeping for 2 seconds
Interval - OnNext(1)
Interval - OnNext(2)
Done sleeping
Interval - OnNext(3)
Interval - OnNext(4)
Interval - OnNext(5)
```

It continues going after that.

Admittedly, 1 out of 10 times that I've run it, I got it to match what the book showed.

But as far as I am concerned the issue is not so much that the `Observable` is not being disposed. Rather, one would expect the opposite - if only the proxy is holding a weak reference to the `Observer` then what is there to stop the GC from disposing it too early?

```
            var subscription =
                Observable.Interval(TimeSpan.FromSeconds(1))
                    .AsWeakObservable()
                    .SubscribeConsole("Interval");
...
            subscription = null;
```

Do weak references really depend on whether their container is reachable? I doubt that is the case as it would make implementing various weak data structures impossible.

**Comment by tamirdresher** [comment]
@mrakgr have you ran it with a debugger attached? if so, try to run it without it

**Comment by mrakgr** [comment]
> have you ran it with a debugger attached?

I did it without the debugger in both Debug and Release mode.

**Comment by tamirdresher** [comment]
@mrakgr i mamanged to reproduced the problem. it's weird that this is happening sporadically on my machine and happens to you most of the time. 
This type of nondeterminism makes me think that this has something to do with how the GC handles the weakreferences.

I profiled the process with a memory profiler when the problem appeared to see what is holding the object.
Interestingly, nothing is holding except for a method variable but no method is actually running. 
![image](https://user-images.githubusercontent.com/342800/78396726-86ac4f00-75f8-11ea-8227-1d074091e69d.png)

I'll hope i would more answers soon

**Comment by mortenbrudvik** [comment]
I have the same issue, when running the example.

**Comment by tamirdresher** [comment]
Thanks for bringing this back again @mortenbrudvik 
I forgot to go back here and update on this.
The reason for this issue is because of poor choice of the example from my side and not due to a bug in the WeakObservable.

Behind the scenes the `Interval` observable created in the example use the `System.Threading.Timer` which maintain a strong reference (with a static member) to the callback used to notify the observer.
You can see this in attached image 
 ![image](https://user-images.githubusercontent.com/342800/129733208-db8e34c4-147b-4676-9e68-bfb3aa855343.png)

The result of this is that the `WeakReference` on the observer would not help here. 
if we change the example and create our own IntervalObservable which doesn't work with System.Threading.Timer you would see that everything works as expected

```csharp
var myIntervalObservable=
    Observable.Create<int>(o =>
    {
        var obsSubscription = new BooleanDisposable();

        Task.Run(async () => {
            int i = 0;
            while (!obsSubscription.IsDisposed)
            {
                o.OnNext(i++);
                await Task.Delay(1000);
            }
            o.OnCompleted();
        });
    
        return obsSubscription;
    });

var subscription =
    myIntervalObservable
        .AsWeakObservable()
        .SubscribeConsole("Interval");

Console.WriteLine("Collecting and sleeping for 2 seconds");
GC.Collect();
Thread.Sleep(2000); //2 seconds 

GC.KeepAlive(subscription);
Console.WriteLine("Done sleeping");
Console.WriteLine("removing the strong reference, collecting and sleeping for 2 seconds");

subscription = null;
GC.Collect();
Thread.Sleep(2000); //2 seconds 
Console.WriteLine("Done sleeping");

Console.ReadLine();

```

cc @mrakgr
